global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: 'fastapi-app'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['fastapi-app:8000']
