# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cart.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cart.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncart.proto\x12\x04\x63\x61rt\"\x13\n\x11\x43reateCartRequest\"%\n\x12\x43reateCartResponse\x12\x0f\n\x07\x63\x61rt_id\x18\x01 \x01(\x05\x32N\n\x0b\x43\x61rtService\x12?\n\nCreateCart\x12\x17.cart.CreateCartRequest\x1a\x18.cart.CreateCartResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cart_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECARTREQUEST']._serialized_start=20
  _globals['_CREATECARTREQUEST']._serialized_end=39
  _globals['_CREATECARTRESPONSE']._serialized_start=41
  _globals['_CREATECARTRESPONSE']._serialized_end=78
  _globals['_CARTSERVICE']._serialized_start=80
  _globals['_CARTSERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
